import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Puneet Shukla',
  description: 'Generated by Next.js',
  icons: {
    icon: '/images/logo.png',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
